# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Spencer Aeschliman
email: aesch.spencer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  There is a time for reciting poems and a time for fists.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://s-aeschliman.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Aeschliman1
github_username:  s-aeschliman
googlescholar_username: citations?user=7gfWWf4AAAAJ&hl=en
flickr_username: 199776332@N03
linkedin_username: spencer-aeschliman-a830aa117
email_username: aesch.spencer@gmail.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
kramdown: 
  math_engine: mathjax
exerpt_seperator: <!--end_exerpt--

flickr:
  api_key: 91880c02c1e7f5e0e30a8caeb9557080

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
